-- -----------------------------------------------------
-- Manifest.sql
--
-- Add migration files in the order they should be
-- executed e.g.
--
-- '\. ./migration/SPRINT/ISSUE_description.sql'
-- '\. ./migration/.example/00001/666_their_satanic_majesties_request.sql'
-- -----------------------------------------------------
